# Generated by Django 6.0.2 on 2026-03-06 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('target_days', models.IntegerField()),
                ('order_index', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_label', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('pneumo_mode', models.CharField(default='Old', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='VaccineFamily',
            fields=[
                ('id_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('linked_antigen_family', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Vaccine Family',
                'verbose_name_plural': 'Vaccine Families',
            },
        ),
        migrations.CreateModel(
            name='PatientVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=100)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('given_date', models.CharField(blank=True, max_length=20, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('diluent_confirmed', models.BooleanField(blank=True, default=False, null=True)),
                ('injection_site', models.CharField(blank=True, max_length=100, null=True)),
                ('eipv_notified', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDose',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pneumo_protocol', models.CharField(max_length=20)),
                ('min_age_days', models.IntegerField(default=0)),
                ('offset_days', models.IntegerField(default=0)),
                ('administration_route', models.CharField(blank=True, max_length=50, null=True)),
                ('default_injection_site', models.CharField(blank=True, max_length=100, null=True)),
                ('vial_lifespan_days', models.IntegerField(default=0)),
                ('advanced_rules_json', models.TextField(blank=True, null=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='api.milestone')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='api.vaccinefamily')),
            ],
            options={
                'verbose_name': 'Vaccine Dose',
                'verbose_name_plural': 'Vaccine Doses',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.patient')),
            ],
        ),
    ]
