# Generated by Django 6.0.2 on 2026-03-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pneumo_mode',
        ),
    ]
