# Generated by Django 6.0.2 on 2026-03-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_patient_pneumo_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinefamily',
            name='catchup_rules_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
